<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="4.045" tests="2" failures="3">
  <testsuite name="Root Suite" timestamp="2022-12-29T16:40:26" tests="0" file="cypress/e2e/suggester.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Expression suggester" timestamp="2022-12-29T16:40:26" tests="2" time="4.006" failures="3">
    <testcase name="Expression suggester &quot;before all&quot; hook for &quot;should display colorfull and sorted completions&quot;" time="0.000" classname="&quot;before all&quot; hook for &quot;should display colorfull and sorted completions&quot;">
      <failure message="`cy.request()` failed trying to load:

http://localhost:3000/api/processes

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/api/processes

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Expression suggester`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:3000/api/processes

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/api/processes

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Expression suggester`
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144280:78)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:6466:37)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9440:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.getTestProcesses (cypress/support/process.ts:107:12)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
      at new r (<embedded>:1:14624732)
      at ee.callback (<embedded>:1:14630733)
      at e.callback.s.callback [as _callback] (<embedded>:1:14630179)
      at s._callback.s.callback.s.callback (<embedded>:219:65245)
      at ee.emit (node:events:527:28)
      at ee.onRequestError (<embedded>:219:74304)
      at ClientRequest.emit (node:events:539:35)
      at Socket.socketErrorListener (node:_http_client:454:9)
      at Socket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)]]></failure>
    </testcase>
    <testcase name="Expression suggester &quot;after all&quot; hook for &quot;should display colorfull and sorted completions&quot;" time="0.000" classname="&quot;after all&quot; hook for &quot;should display colorfull and sorted completions&quot;">
      <failure message="`cy.request()` failed trying to load:

http://localhost:3000/api/processes

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/api/processes

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Expression suggester`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:3000/api/processes

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/api/processes

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Expression suggester`
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144280:78)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:6466:37)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9440:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.getTestProcesses (cypress/support/process.ts:107:12)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
      at new r (<embedded>:1:14624732)
      at ee.callback (<embedded>:1:14630733)
      at e.callback.s.callback [as _callback] (<embedded>:1:14630179)
      at s._callback.s.callback.s.callback (<embedded>:219:65245)
      at ee.emit (node:events:527:28)
      at ee.onRequestError (<embedded>:219:74304)
      at ClientRequest.emit (node:events:539:35)
      at Socket.socketErrorListener (node:_http_client:454:9)
      at Socket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)]]></failure>
    </testcase>
    <testcase name="Expression suggester &quot;after all&quot; hook: collectBackendCoverage for &quot;should display colorfull and sorted completions&quot;" time="0.000" classname="&quot;after all&quot; hook: collectBackendCoverage for &quot;should display colorfull and sorted completions&quot;">
      <failure message="`cy.request()` failed trying to load:

http://localhost:3000/__coverage__

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/__coverage__

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after all` hook we are skipping all of the remaining tests." type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:3000/__coverage__

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: http://localhost:3000/__coverage__

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144280:78)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:6466:37)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9440:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.collectBackendCoverage (node_modules/@cypress/code-coverage/support.js:149:0)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
      at new r (<embedded>:1:14624732)
      at ee.callback (<embedded>:1:14630733)
      at e.callback.s.callback [as _callback] (<embedded>:1:14630179)
      at s._callback.s.callback.s.callback (<embedded>:219:65245)
      at ee.emit (node:events:527:28)
      at ee.onRequestError (<embedded>:219:74304)
      at ClientRequest.emit (node:events:539:35)
      at Socket.socketErrorListener (node:_http_client:454:9)
      at Socket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>